[package]
name = "readlogs-macros"
version = "0.1.0"
edition = "2021"
readme = "../README.md"
license = "MIT"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
