on: [push, pull_request]
name: Rust
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Install Trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.14.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Install CSS dependencies
        run: yarn install
      - name: "Trunk: build"
        run: ./trunk build
      - name: "Rust: test"
        run: cargo test
      - name: "Rust: clippy"
        run: cargo clippy
      - name: "Rust: rustfmt check"
        run: cargo fmt --all -- --check
